#!/usr/bin/env python

from __future__ import print_function

import argparse
import itertools
import os
import re
import subprocess
import sys
import time

YES = ['yes', 'Yes', 'YES', 'y', 'Y', 'true', 'True', 'TRUE', 't', 'T']
NO  = ['no', 'No', 'NO', 'n', 'N', 'false', 'False', 'FALSE', 'f', 'F']

quiet = False
suppress_comments = False

def printq(msg, end = '\n'):
    if not quiet:
        print(msg, end = end)


def create_parser():
    parser = argparse.ArgumentParser(prefix_chars = '-')
    parser.add_argument('kelf')
    parser.add_argument('--args', '-a', nargs = '*', default = [])
    parser.add_argument('--suppress-comments', '-sc', action = 'store_true')
    parser.add_argument('--regex', '-r', action = 'append', default = [])
    parser.add_argument('--perf-file')
    parser.add_argument('--regex-file')
    parser.add_argument('--quiet', '-q', action = 'store_true')
    return parser


def parse_kelf_args(kargs):
    if len(kargs) == 0:
        return {}
    ret = {}
    arg_name = None
    for i in range(len(kargs)):
        if kargs[i][0] != '[':
            # it's an argument name
            arg_name = kargs[i].strip()
        else:
            if arg_name == None:
                pass
            # it is a range or a value set
            if kargs[i][-1] != ']':
                raise 'values must be enclosed in brackets'
                pass
            vals = kargs[i][1:-1]
            # try range
            if ':' in vals:
                svals = vals.split(':')
                if len(svals) == 3:
                     # range syntax
                    try:
                        start = int(svals[0])
                        stop = int(svals[1])
                        step = int(svals[2])
                        rng = range(start, stop, step)
                        ret[arg_name] = rng
                        arg_name = None
                    except ValueError:
                        raise 'a range of values must have integer boundaries'
                        pass
            elif '_' in vals:
                svals = vals.split('_')
                if len(svals) == 0:
                    raise 'Invalid syntax'
                    pass
                ret[arg_name] = svals
                arg_name = None
            else:
                ret[arg_name] = [vals]
                arg_name = None
    return ret


def permute_args(parsed_kelf_args):
    ll = []
    for arg_name in parsed_kelf_args:
        ll.append(parsed_kelf_args[arg_name])
    return list(itertools.product(*ll))


def build_command(kelf_file_name, arg_names, arg_values):
    command = ['k1-jtag-runner']
    command.append('--exec-file=Cluster0:' + kelf_file_name)
    command.append('--')
    for i in range(len(arg_values)):
        n = arg_names[i]
        v = arg_values[i]
        arg_prefix = '--'
        if len(n) == 1:
            arg_prefix = '-'
        arg_str = ''
        if v in YES:
            arg_str = arg_prefix + n
            command.append(arg_str)
        elif v in NO:
            command.append(arg_str)
            continue
        else:
            arg_str = arg_prefix + n
            command.append(arg_str)
            command.append(str(v))
    return command


def get_test_name_with_args(kelf_file_name, arg_names, arg_values):
    t = kelf_file_name.split('/')[-1]
    ret = t[: t.rfind('.')]
    for i in range(len(arg_values)):
       v = arg_values[i]
       if v in YES:
            ret = ret + '_' + arg_names[i]
            continue
       if v in NO:
            continue
       ret = ret + '_' + arg_names[i] + ':' + str(v)
    if 'mos' in kelf_file_name:
        ret = ret + '_mos'
    if 'nodeos' in kelf_file_name:
        ret = ret + '_nodeos'
    return ret


def open_perff(perff_name):
    dir = os.path.dirname(perff_name)
    if not os.path.exists(dir):
        os.makedirs(dir)
    try:
        f = open(perff_name, 'a')
        return f
    except:
        return None

def get_regex_from_file(regexf_name, store_in):
    try:
        regex_file = open(regexf_name, 'r')
        store_in.extend(regex_file.read().splitlines())
    except:
        pass 


def main():
    parser = create_parser()
    script_args = parser.parse_args()

    global suppress_comments
    suppress_comments = script_args.suppress_comments
    kelf_args_matrix = parse_kelf_args(script_args.args)
    permutations = permute_args(kelf_args_matrix)
    regex_args = script_args.regex

    perf_file_name = script_args.perf_file
    regex_file_name = script_args.regex_file

    global quiet
    quiet = script_args.quiet

    for i in range(len(permutations)):
        command = build_command(script_args.kelf, kelf_args_matrix.keys(), permutations[i])
        printq('#' + '-' * 80)
        printq('# Running test: ' + ' '.join(command))
        printq('#' + '-' * 80)
        stdoutdata = ''

        job = subprocess.Popen(command, stdout = subprocess.PIPE)
        try:
            while True:
                line = job.stdout.readline()
                if line:
                    line = '# ' + line 
                    stdoutdata = stdoutdata + line
                    printq(line, end = '')
                else:
                    break
        except:
            job.terminate()
            job.wait()
            sys.exit(job.returncode)
        
        job.wait()
        if job.returncode != 0:
            sys.exit(job.returncode)

        get_regex_from_file(regex_file_name, regex_args)
        
        matched_results = {}
        for r in regex_args:
            l = r.split('::')
            exp = l[0]
            compiled_exp = re.compile(exp)
            match = compiled_exp.search(stdoutdata)
            if match:
                for j in range(1, compiled_exp.groups + 1):
                    metric = l[j]
                    matched_results[metric] = match.group(j)

        test_name = get_test_name_with_args(script_args.kelf, kelf_args_matrix.keys(), permutations[i])

        f = None
        if perf_file_name is not None:
            f = open_perff(perf_file_name)
            if f is not None:
                f.write(stdoutdata)
        
        for metric in matched_results:
            print(metric + ' ' + test_name + ' ' + matched_results[metric])
            if f is not None:
                f.write(metric + ' ' + test_name + ' ' + matched_results[metric] + '\n') 


if __name__ == '__main__':
    main()
