ifndef __IOETH_BSP_INCLUDED__
__IOETH_BSP_INCLUDED__ := 1

# Add magic for BSP here
IOETHBSP_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
SRCDIRS  += $(IOETHBSP_DIR)

_CFLAGS  += -DLINUX_FIRMWARE -DUNUSABLE_TX=3 -DUNUSABLE_RX=128  -DDDR_BASE_ADDR=0xB8200000
_LDFLAGS +=-T$(IOETHBSP_DIR)/platform.ld -L$(IOETHBSP_DIR)  -Wl,--defsym=K1_BOOT_ADDRESS=0xB8000000 -Wl,--defsym=K1_EXCEPTION_ADDRESS=0xB8000400  -Wl,--defsym=K1_INTERRUPT_ADDRESS=0xB8000800 -Wl,--defsym=K1_SYSCALL_ADDRESS=0xB8000c00 -Wl,--allow-multiple-definition

endif
